services:
  app:
    build:
      context: .
      dockerfile: ./docker/backend.Dockerfile
    environment:
      - APP_ENV=prod
    ports:
      - "9123:9000"
    depends_on:
      - database
    volumes:
      - ./:/var/www/app

  web:
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - app
    volumes:
      - ./:/var/www/app
  database:
    image: postgres:18
    environment:
      POSTGRES_DB: "pablo_romero"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --auth-host=trust
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5477:5432"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql

volumes:
  db-data:
